In [37]:
## Necessary packages
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import warnings
warnings.filterwarnings("ignore")

# 1. TimeGAN model
# from TimeGAN.timegan import timegan
# 2. Data loading
from TimeGAN.data_loading import real_data_loading, sine_data_generation
# 3. Metrics
# from TimeGAN.metrics.discriminative_metrics import discriminative_score_metrics
# from TimeGAN.metrics.predictive_metrics import predictive_score_metrics
# from TimeGAN.metrics.visualization_metrics import visualization

In [11]:
# activate line execution
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [20]:
import plotly.express as px

In [5]:
import pandas as pd
import numpy as np
import pickle

In [28]:
## Data loading
data_name = 'stock'
seq_len = 24

if data_name in ['stock', 'energy']:
  ori_data = real_data_loading(data_name, seq_len)
elif data_name == 'sine':
  # Set number of samples and its dimensions
  no, dim = 10000, 5
  ori_data = sine_data_generation(no, seq_len, dim)
    
print(data_name + ' dataset is ready.')

stock dataset is ready.


In [ ]:
metric_iteration = 5

discriminative_score = list()
for _ in range(metric_iteration):
  temp_disc = discriminative_score_metrics(ori_data, generated_data)
  discriminative_score.append(temp_disc)

print('Discriminative score: ' + str(np.round(np.mean(discriminative_score), 4)))

In [33]:
len(ori_data)
ori_data[0][:5]

3661

array([[0.08575867, 0.08862951, 0.0867335 , 0.08882463, 0.08882463,
        0.14398467],
       [0.0809403 , 0.08477182, 0.08199468, 0.08485422, 0.08485422,
        0.163604  ],
       [0.08164375, 0.08317594, 0.08000984, 0.07781021, 0.07781021,
        0.1573075 ],
       [0.08458762, 0.08464593, 0.08199468, 0.08501728, 0.08501728,
        0.17586352],
       [0.08835286, 0.08825592, 0.08546402, 0.08382289, 0.08382289,
        0.1587321 ]])

In [34]:
with open('data/stock.pkl', 'rb') as f:
    ori_data2 = pickle.load(f)



In [7]:
df = pd.read_csv('TimeGAN/data/stock_data.csv')

In [35]:
ori_data2.keys()
ori_data2['train_set']
len(ori_data2['train_set'])
ori_data2['train_set'][0]['dyn'][:5]
ori_data2['train_set'][1]['dyn'][:5]
ori_data2['train_set'][2]['dyn'][:5]

dict_keys(['train_set', 'dynamic_processor', 'static_processor'])

+---------+------------------------------+-----+
| seq_len | dyn                          | sta |
+---------+------------------------------+-----+
| 24      | [[0.93861141 0.94147215 0... | 0   |
| 24      | [[0.94834356 0.94670361 0... | 0   |
| 24      | [[0.954155   0.95285887 0... | 0   |
| 24      | [[0.9467474  0.95240934 0... | 0   |
| 24      | [[0.94800794 0.95292433 0... | 0   |
| 24      | [[0.93805478 0.94070371 0... | 0   |
| 24      | [[0.92887107 0.93687002 0... | 0   |
| 24      | [[0.92134078 0.92242602 0... | 0   |
| 24      | [[0.91859058 0.91635658 0... | 0   |
| 24      | [[0.93001701 0.92943054 0... | 0   |
| 24      | [[0.94068228 0.94191349 0... | 0   |
| 24      | [[0.93937268 0.94483007 0... | 0   |
| ...     | ...                          | ... |
+---------+------------------------------+-----+

3661

array([[0.93861141, 0.94147215, 0.95343567, 0.94167311, 0.94167311,
        0.01036247],
       [0.94834356, 0.94670361, 0.95907934, 0.94708071, 0.94708071,
        0.01029843],
       [0.954155  , 0.95285887, 0.96338287, 0.94979688, 0.94979688,
        0.01086633],
       [0.9467474 , 0.95240934, 0.96263369, 0.95623843, 0.95623843,
        0.01138349],
       [0.94800794, 0.95292433, 0.95961209, 0.94878758, 0.94878758,
        0.01220273]])

array([[0.94834356, 0.94670361, 0.95907934, 0.94708071, 0.94708071,
        0.01029843],
       [0.954155  , 0.95285887, 0.96338287, 0.94979688, 0.94979688,
        0.01086633],
       [0.9467474 , 0.95240934, 0.96263369, 0.95623843, 0.95623843,
        0.01138349],
       [0.94800794, 0.95292433, 0.95961209, 0.94878758, 0.94878758,
        0.01220273],
       [0.93805478, 0.94070371, 0.94730091, 0.94433178, 0.94433178,
        0.00990814]])

array([[0.954155  , 0.95285887, 0.96338287, 0.94979688, 0.94979688,
        0.01086633],
       [0.9467474 , 0.95240934, 0.96263369, 0.95623843, 0.95623843,
        0.01138349],
       [0.94800794, 0.95292433, 0.95961209, 0.94878758, 0.94878758,
        0.01220273],
       [0.93805478, 0.94070371, 0.94730091, 0.94433178, 0.94433178,
        0.00990814],
       [0.92887107, 0.93687002, 0.94421275, 0.93935911, 0.93935911,
        0.01503863]])

In [9]:
df

Open         High          Low        Close    Adj_Close  \
0       49.676899    51.693783    47.669952    49.845802    49.845802   
1       50.178635    54.187561    49.925285    53.805050    53.805050   
2       55.017166    56.373344    54.172661    54.346527    54.346527   
3       55.260582    55.439419    51.450363    52.096165    52.096165   
4       52.140873    53.651051    51.604362    52.657513    52.657513   
...           ...          ...          ...          ...          ...   
3680  1207.479980  1216.300049  1200.500000  1205.920044  1205.920044   
3681  1205.939941  1215.670044  1204.130005  1215.000000  1215.000000   
3682  1214.989990  1216.219971  1205.030029  1207.150024  1207.150024   
3683  1207.890015  1208.689941  1199.859985  1203.839966  1203.839966   
3684  1196.000000  1202.290039  1193.079956  1197.250000  1197.250000   

        Volume  
0     44994500  
1     23005800  
2     18393200  
3     15361800  
4      9257400  
...        ...  
3680   1017800  
3681    950000  
3682    907200  
3683    860200  
3684    865500  

[3685 rows x 6 columns]

In [22]:
px.line(df, x=df.index, y='Open', title='Stock Price')
px.line(df, x=df.index, y='Volume', title='Stock Price')

# Data Loading