# Intro

* the goal is to evaluate the quality of generated data

In [1]:
# activate line execution
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [48]:
import pickle
import numpy as np

# plotly
import plotly.express as px  # (version 4.7.0 or higher)
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [3]:
add_data = '2012_result/test/2012.pkl'

with open(add_data, 'rb') as f:
    dataset = pickle.load(f)

In [13]:
dataset.keys()

sta, dyn = dataset['train_set']

type(sta), sta.shape

len(dyn), dyn[0].shape, dyn[1].shape

dyn[0]

dict_keys(['train_set', 'raw_set', 'test_set', 'val_set', 'dynamic_processor', 'static_processor'])

(pandas.core.frame.DataFrame, (3594, 7))

(3594, (76, 36), (82, 36))

time  Albumin  ALP  ALT  AST  Bilirubin  BUN  Cholesterol  Creatinine  \
0     20.0      NaN  NaN  NaN  NaN        NaN  NaN          NaN         NaN   
1     38.0      NaN  NaN  NaN  NaN        NaN  NaN          NaN         NaN   
2     54.0      NaN  NaN  NaN  NaN        NaN  NaN          NaN         NaN   
3     66.0      NaN  NaN  NaN  NaN        NaN  NaN          NaN        49.0   
4     76.0      NaN  NaN  NaN  NaN        NaN  NaN          NaN        50.0   
..     ...      ...  ...  ...  ...        ...  ...          ...         ...   
71  1026.0      NaN  NaN  NaN  NaN        NaN  NaN          NaN         NaN   
72  1044.0      NaN  NaN  NaN  NaN        NaN  NaN          NaN         NaN   
73  1061.0      NaN  NaN  NaN  NaN        NaN  NaN          NaN         NaN   
74  1078.0      NaN  NaN  NaN  NaN        NaN  NaN          NaN         NaN   
75  1094.0      NaN  NaN  NaN  NaN        NaN  NaN          NaN         NaN   

    DiasABP  ...      PaO2  pH  Platelets  RespRate   SaO2  SysABP  Temp  \
0       NaN  ...  7.861921 NaN        NaN       NaN    NaN     NaN   NaN   
1       NaN  ...       NaN NaN        NaN       NaN    NaN     NaN   NaN   
2   0.65353  ...       NaN NaN        NaN       NaN    NaN     NaN   NaN   
3       NaN  ...       NaN NaN        NaN       NaN  106.0     NaN   NaN   
4       NaN  ...       NaN NaN        NaN       NaN  108.0     NaN   NaN   
..      ...  ...       ...  ..        ...       ...    ...     ...   ...   
71      NaN  ...       NaN NaN        NaN       NaN    NaN     NaN   NaN   
72      NaN  ...       NaN NaN        NaN       NaN    NaN     NaN   NaN   
73      NaN  ...       NaN NaN        NaN       NaN    NaN     NaN   NaN   
74      NaN  ...       NaN NaN        NaN       NaN    NaN     NaN   NaN   
75      NaN  ...       NaN NaN        NaN       NaN    NaN     NaN   NaN   

    TroponinI   TroponinT  Urine  
0         NaN         NaN    NaN  
1         NaN         NaN    NaN  
2         NaN         NaN    NaN  
3         NaN  137.548599    NaN  
4         NaN         NaN    NaN  
..        ...         ...    ...  
71        NaN         NaN    NaN  
72        NaN         NaN    NaN  
73        NaN         NaN    NaN  
74        NaN         NaN    NaN  
75        NaN         NaN    NaN  

[76 rows x 36 columns]

In [15]:
add_raw = 'data/physio_data/full2012.pkl'

with open(add_raw, 'rb') as f:
    rawset = pickle.load(f)
    

In [16]:
rawset.keys()

dict_keys(['train_set', 'raw_set', 'test_set', 'val_set', 'dynamic_processor', 'static_processor'])

In [46]:
np.array((rawset['train_set'])[0]['dyn']).shape
rawset['train_set'][0]




(50, 35)

+---------+--------------+--------------+--------------+--------------+--------------+--------------+--------------+-------+
| seq_len | dyn          | lag          | mask         | sta          | times        | priv         | nex          | label |
+---------+--------------+--------------+--------------+--------------+--------------+--------------+--------------+-------+
| 50      | [[0.0, 0.... | [[0.00243... | [[0.0, 0.... | [0.52 0. ... | [[0.00243... | [[0.0, 0.... | [[0.0, 0.... | 0.0   |
+---------+--------------+--------------+--------------+--------------+--------------+--------------+--------------+-------+

# Missing pattern

In [84]:
# [x.shape for x in temp]
temp = [ np.array(sample['mask'], dtype=int)   for sample in rawset['train_set'] ]

X = np.concatenate(temp, axis=0)

X.shape
(X.sum(0)/X.shape[0]*100).round(1)

px.imshow(X[:120])

(266211, 35)

array([ 1. ,  1.1,  1.1,  1.1,  4.7,  0.1,  4.7, 49.3, 10.9, 20.7,  4.4,
        4.6,  6.2, 77.4,  4.9,  2.7,  4.6, 48.7, 10.5,  4.6, 33.3, 32.8,
       33.3,  7.9,  7.9,  8.2,  4.8, 18.4,  2.8, 49.3, 29.3,  0.1,  0.7,
       45.8,  4.4])

In [87]:
sta0, dyn0 = rawset['test_set']
sta, dyn = dataset['test_set']

(dyn[0].notnull()*1).values.shape

temp = [ (sample.notnull()*1).values   for sample in dataset['test_set'][1] ]

X= np.concatenate(temp, axis=0)[:,1:]
(X.sum(0)/X.shape[0]*100).round(1)

px.imshow(X[:120])

(44, 36)

array([ 1.1,  1.1,  1.1,  1.1,  4.7,  0.1,  4.7, 49.5, 11.6, 22.2,  4.4,
        4.6,  6. , 77.4,  5. ,  2.6,  4.6, 49. , 10.7,  4.7, 33.2, 32.7,
       33.2,  8. ,  8. ,  8.4,  4.6, 20.3,  2.8, 49.5, 27.7,  0.1,  0.8,
       45.8,  4.3])

# missing rate

In [79]:
# [x.shape for x in temp]
temp = [ np.array(sample['mask'], dtype=int)   for sample in rawset['train_set'] ]

X = np.concatenate(temp, axis=0)

(X.sum(0)/X.shape[0]*100).round(1)

px.imshow(X[:120])

array([ 1. ,  1.1,  1.1,  1.1,  4.7,  0.1,  4.7, 49.3, 10.9, 20.7,  4.4,
        4.6,  6.2, 77.4,  4.9,  2.7,  4.6, 48.7, 10.5,  4.6, 33.3, 32.8,
       33.3,  7.9,  7.9,  8.2,  4.8, 18.4,  2.8, 49.3, 29.3,  0.1,  0.7,
       45.8,  4.4])

In [80]:
sta0, dyn0 = rawset['test_set']
sta, dyn = dataset['test_set']

(dyn[0].notnull()*1).values.shape

temp = [ (sample.notnull()*1).values   for sample in dataset['test_set'][1] ]

X= np.concatenate(temp, axis=0)

(X.sum(0)/X.shape[0]*100).round(1)

px.imshow(X[:120])

(44, 36)

array([100. ,   1.1,   1.1,   1.1,   1.1,   4.7,   0.1,   4.7,  49.5,
        11.6,  22.2,   4.4,   4.6,   6. ,  77.4,   5. ,   2.6,   4.6,
        49. ,  10.7,   4.7,  33.2,  32.7,  33.2,   8. ,   8. ,   8.4,
         4.6,  20.3,   2.8,  49.5,  27.7,   0.1,   0.8,  45.8,   4.3])

In [21]:
sta0.shape, sta.shape

sta0.sum()
sta.sum()

((400, 7), (400, 7))

Age        25210.00
Gender       222.00
Height     35285.50
ICUType     1110.00
Weight     30755.18
Label         50.00
seq_len    29050.00
dtype: float64

Age        25210.00
Gender       222.00
Height     35285.50
ICUType     1110.00
Weight     30755.18
Label         50.00
seq_len    29050.00
dtype: float64