In [14]:
import torch
import torch.nn.functional as F
import plotly.graph_objects as go

# Generate a random binary matrix of size [W, H]
W, H = 20, 5
binary_matrix = torch.randint(0, 2, size=(W, H), dtype=torch.float32)

# Define the standard deviation for the Gaussian kernel
sigma = 1

# Create the Gaussian kernel
kernel_size = int(6 * sigma) + 1
gaussian_kernel = torch.exp(-(torch.arange(kernel_size) - kernel_size // 2)**2 / (2 * sigma**2))
gaussian_kernel = gaussian_kernel / gaussian_kernel.sum()

# Apply Gaussian smoothing using convolution
smoothed_matrix = F.conv1d(binary_matrix.view(1, 1, -1), 
                            gaussian_kernel.view(1, 1, -1), 
                            padding=kernel_size // 2)
smoothed_matrix = smoothed_matrix.view(W, H)

# Plot the original and smoothed matrices using Plotly
original_heatmap = go.Heatmap(z=binary_matrix.numpy(), colorscale="Viridis")
smoothed_heatmap = go.Heatmap(z=smoothed_matrix.numpy(), colorscale="Viridis")

fig = go.Figure(data=[original_heatmap],
                layout=go.Layout(title="Original vs Smoothed Binary Matrix"))
fig.show()

fig = go.Figure(data=[smoothed_heatmap],
                layout=go.Layout(title="Original vs Smoothed Binary Matrix"))
fig.show()




In [15]:
binary_matrix[0]

tensor([1., 1., 0., 1., 0.])

In [5]:
gaussian_kernel

tensor([0.0022, 0.0088, 0.0270, 0.0648, 0.1211, 0.1762, 0.1997, 0.1762, 0.1211,
        0.0648, 0.0270, 0.0088, 0.0022])

In [6]:
binary_matrix.view(1, 1, -1).shape

torch.Size([1, 1, 500])

In [55]:
binary_matrix.shape

torch.Size([100, 5])

tensor([[ True,  True,  True,  True,  True],
        [False,  True,  True,  True,  True],
        [ True, False,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True, False,  True,  True],
        [ True, False,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True, False,  True,  True],
        [ True, False,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True, False,  True],
        [ True,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False,  True,  True,  True,  True],
        [ True, False,  True,  True, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True],
        [ 

In [65]:
kernel.shape

torch.Size([5, 1, 3])

In [66]:
kernel[0,0]

tensor([0.3311, 0.3378, 0.3311])

In [80]:
import torch
import torch.nn.functional as F
import plotly.graph_objs as go

# Create a binary matrix
W, H = 100, 5
kernel_size = 9
sigma = 1


binary_matrix = torch.randint(0, 2, (W, H), dtype=torch.float32)
binary_matrix = (torch.rand((W,H))>0.95).float()
# Define the Gaussian kernel

kernel = torch.exp(-(torch.arange(kernel_size) - kernel_size // 2)**2 / (2 * sigma**2))
kernel = kernel / kernel.sum()

# Convert the kernel to a 2D tensor
kernel = kernel.expand(H,1,-1)

# Apply convolution to smoothen along the first dimension
smoothed_matrix = F.conv1d(binary_matrix.unsqueeze(0).transpose(1,2), kernel, padding='same', groups=H).transpose(1,2)

# Plotting using Plotly
original_trace = go.Heatmap(z=binary_matrix.numpy(), colorscale='Viridis', name='Original')
smoothed_trace = go.Heatmap(z=smoothed_matrix[0].numpy(), colorscale='Viridis', name='Smoothed')

layout = go.Layout(title='Binary Matrix Smoothing Along First Dimension',
                   xaxis=dict(title='Second Dimension'),
                   yaxis=dict(title='First Dimension'))

fig = go.Figure(data=[original_trace], layout=layout)
fig.show()

fig = go.Figure(data=[smoothed_trace], layout=layout)
fig.show()


In [33]:
kernel.shape

torch.Size([5, 5, 5])

In [42]:
binary_matrix.unsqueeze(0).transpose(1,2).shape

torch.Size([1, 5, 20])

In [41]:
F.conv1d(binary_matrix.unsqueeze(0), kernel, padding=kernel_size // 2, groups=1)

RuntimeError: Given groups=1, weight of size [5, 5, 5], expected input[1, 20, 5] to have 5 channels, but got 20 channels instead

In [44]:
smoothed_matrix.transpose(1,2).shape

torch.Size([1, 20, 5])